### ISSUE TITLE
Can not get a connection

### ISSUE THREAD

**Issue by bjanczak** [swaldman/c3p0#103]
I run a multitenant web application. On our production environment some of our tenants requests can not connect to database.
This happened after our connection pool run out of connections and I have manually hard resetted pool via JMX.
Since that time only specific tenants, can not connect to database. We use Tomcat 8 application server and have infinite sessions set up. Despite the fact there are only few connections used out of 250 tenants can not get connection.

Our c3p0 configuration is attached.
![java visualvm 2017-12-04 09-53-52](https://user-images.githubusercontent.com/2887291/33545741-60b08a18-d8df-11e7-89ed-cccc501cfa73.png)
![java visualvm 2017-12-04 09-53-36](https://user-images.githubusercontent.com/2887291/33545742-60ca0894-d8df-11e7-913d-cfd1a50f0db9.png)

The stacktrace we experiance:
```
at com.softwareplant.util.multitenancy.infrastructure.TenantCacheLoader.load(TenantCacheLoader.java:12)
	at com.softwareplant.util.cacheint.ehcache3.EhCache3LoaderWriter.load(EhCache3LoaderWriter.java:21)
	at org.ehcache.core.EhcacheWithLoaderWriter$2.apply(EhcacheWithLoaderWriter.java:222)
	... 25 more
Caused by: java.sql.SQLException: An SQLException was provoked by the following failure: java.lang.InterruptedException
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:74)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:694)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:139)
	at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:380)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:228)
	... 51 more
Caused by: java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1465)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)
	... 55 more
```

**Comment by swaldman** [comment]
I think that these stack traces do not come from interacting with the DataSource whose JMX mbean properties you are showing. Do you see any other c3p0 DataSources among your mbeans?

**Comment by bjanczak** [comment]
There is other data source but we have no problem with connections there. 
Configuration:
![java visualvm 2017-12-04 12-14-12](https://user-images.githubusercontent.com/2887291/33550061-e4076b54-d8ec-11e7-9792-6f47b57f1339.png)
![java visualvm 2017-12-04 12-13-20](https://user-images.githubusercontent.com/2887291/33550062-e41f25aa-d8ec-11e7-8aeb-c5cd41384214.png)

**Comment by bjanczak** [comment]
What might be the cause of the problem?

**Comment by liuziangexit** [comment]
@bjanczak 
![image](https://user-images.githubusercontent.com/15322450/40961445-39a5e6b2-68d5-11e8-9623-8da6b2c4a13a.png)

same problem...did you solve it? can you tell me how? im appreciated.

**Comment by liuziangexit** [comment]
well, i have solved it.
in my situation, this is cause by connection leak in old version c3p0.
our team is using a 2006 built of c3p0, and looks like it have some connection leak problem.
and i just simply changed it to the latest version, and everything works good.

**Comment by Priyaranjan0007** [comment]
@liuziangexit what was the old version and new version of c3p0?
