### ISSUE TITLE
java.lang.InternalError: Marking a ResultSet inactive that we did not know was opened!

### ISSUE THREAD

**Issue by crowmagnumb** [swaldman/c3p0#104]
Using c3p0 connection to perform a simple SQL SELECT statement using postgres I get the following error if I use ```statement.executeQuery()``` ...

```
java.lang.InternalError: Marking a ResultSet inactive that we did not know was opened!
```

... but if I use ```statement.execute()``` it's fine. What is going on there? Here is my code where ```connectionProvider``` is a ```ComboPooledDataSource``` ....

```
Connection connection = connectionProvider.getConnection();
Statement statement = connection.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
ResultSet rs = statement.executeQuery();
```

After stepping through the ResultSet I perform a ```statement.close()``` and get ...

```
java.lang.InternalError: Marking a ResultSet inactive that we did not know was opened!
	at com.mchange.v2.c3p0.impl.NewPooledConnection.markInactiveResultSetForStatement(NewPooledConnection.java:353)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.close(NewProxyResultSet.java:844)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.close(NewProxyStatement.java:162)
```

If, however, sub ```statement.execute()``` for ```statement.executeQuery()``` I don't have this problem.

**Comment by 4shotespresso** [comment]
Any resolution to this, besides switching to statement.execute()?

**Comment by 4shotespresso** [comment]
If it helps, my bug was a matter of accessing a ResultSet on the PreparedStatement vs on the DBConnection object.  Not a C3P0 issue.

BAD
2245 | < | while(dbCon.getPrepStmt().getResultSet().next()){
2246 | < | int count = dbCon.getPrepStmt().getResultSet().getInt("c");

GOOD
2245 | > | while(dbCon.getResultSet().next()){
2246 | > | int count = dbCon.getResultSet().getInt("c");
