### ISSUE TITLE
Exception while getting connection

### ISSUE THREAD

**Issue by bjanczak** [swaldman/c3p0#112]
C3P0 version: 0.9.5.2
I get following exception:
`Caused by: java.sql.SQLException: An SQLException was provoked by the following failure: java.lang.InterruptedException
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:74)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:694)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)`

My c3p0 configuration:
![java visualvm 2018-02-14 14-05-25](https://user-images.githubusercontent.com/2887291/36205781-34c54d46-1190-11e8-9562-c453da241bfa.png)
![java visualvm 2018-02-14 14-05-07](https://user-images.githubusercontent.com/2887291/36205782-34f47918-1190-11e8-8fbf-eecc208ceca8.png)

**Comment by rangareddy** [comment]
HI Swaldman,

Have u resolved above issue. I am also facing same issue. Please let me know if you resolved.
