### ISSUE TITLE
Blocked calling BasicResourcePool.checkoutResource() during database disconnection.

### ISSUE THREAD

**Issue by matzoliv** [swaldman/c3p0#120]
Hi,

After a database connection loss, our application ended up blocked waiting for a `BasicResourcePool.checkoutResource` method call to return. It stayed blocked that way for quite a while and we were able to study a heap dump closely, but as I realized later, it was not completely deadlocked : with the database back online, after I forced another call to `BasicResourcePool.checkoutResource`, things got unstuck. The following is my hypothesis on the problem. I did my best to figure out the intention of the code, but I did make assumptions here and there. I apologize in advance if my report ends up being incorrect.

Note: the problem occurred using version 0.9.1.1, but I have strong reason to believe it can occur with the latest version also.

The problem seems to be located in the `com.mchange.v2.resourcepool.BasicResourcePool` class.

- After the database disconnected, I assume that refurbishing resources failed, eventually leading to an empty `managed` hash map. This situation seems to be expected.
- Subsequent `checkoutResource()` lead to multiple `AcquireTask`s being scheduled. In newer version `ScatteredAcquireTask` is used instead, but I believe what I will describe is still possible.
- `mgr.acquireResource()` continues to fail because the database is still disconnected.
- Because of this, multiple `AcquireTask`s will end up calling `forceKillAcquires()` _concurrently_.
- `forceKillAcquires()` is synchronized, but it also calls `this.wait()` which releases the lock. Therefore concurrent calls to `forceKillAcquires()` _can be interleaved_, as illustrated by the following stacks in my heap dump.

  A thread is blocked waiting inside `forceKillAcquires()`

<img width="890" alt="screen shot 2018-11-16 at 12 27 30 pm" src="https://user-images.githubusercontent.com/4600649/48637656-5d0b6d00-e99c-11e8-8744-56e3335f6b7a.png">

But the `force_kill_acquires` boolean is false at the same time

<img width="872" alt="screen shot 2018-11-16 at 12 28 24 pm" src="https://user-images.githubusercontent.com/4600649/48637683-72809700-e99c-11e8-8730-2a683aa2bbe9.png">

- This state make so that `pending_acquires` is never decremented and stays > 0 indefinitively.

<img width="597" alt="screen shot 2018-11-16 at 12 29 35 pm" src="https://user-images.githubusercontent.com/4600649/48637646-55e45f00-e99c-11e8-9c0e-d3079a590061.png">

- At the same time, another attempt at checking out a resource is done, which ends up calling `awaitAvailable()`. A comment block seems to describe something very similar to our situation : empty `managed` and a possibility of nothing scheduled to call `notifyAll`.

```
                // the if case below can only occur when 2) a user attempts a
                // checkout which would provoke an acquire; 2) this
                // increments the pending acquires, so we go to the
                // wait below without provoking postAcquireMore(); 3)
                // the resources are acquired; 4) external management
                // of the pool (via for instance unpoolResource()
                // depletes the newly acquired resources before we
                // regain this' monitor; 5) we fall into wait() with
                // no acquires being scheduled, and perhaps a managed.size()
                // of zero, leading to deadlock. This could only occur in
                // fairly pathological situations where the pool is being
                // externally forced to a very low (even zero) size, but
                // since I've seen it, I've fixed it.
                if (pending_acquires == 0 && managed.size() < max)
                    _recheckResizePool();
```

It's therefore attempting to schedule new `AcquireTask` through `_recheckResizePool()` to make sure something will end up calling `notifyAll`. But here we see that it assumes this can only occur if `pending_acquires == 0`. It probably assumes also that if something was inside `forceKillAcquires`, the `force_kill_acquires` would be true leading to an early exit of the method (but we know it's not necessarily the case because because they can be interleaved).

- This ends up blocking indefinitely on the `this.wait()` call inside `awaitAvailable()` because nothing is scheduled to call `notifyAll`.

<img width="1283" alt="screen shot 2018-11-16 at 12 41 45 pm" src="https://user-images.githubusercontent.com/4600649/48638023-71039e80-e99d-11e8-9e41-1b4c7253af2f.png">

<img width="855" alt="screen shot 2018-11-16 at 12 43 18 pm" src="https://user-images.githubusercontent.com/4600649/48638002-59c4b100-e99d-11e8-8a3a-bc3d8bd91d14.png">

- Infering all this, I deduced that forcing some more `AcquireTask` though other parallel `checkout` would unstuck the situation. I had a way to try this on the live locked system and it did just that.

## Solution suggestion

I believe the main broken assumption here is that `forceKillAcquires` concurrent calls cannot be intervealed. To make this assumption correct we could test if `force_kill_acquires` is not already set to true and returning early if it's the case, like so :

```
    private synchronized void forceKillAcquires() throws InterruptedException
    {
       ...
        try
        {
            if (force_kill_acquires)
                return;
            force_kill_acquires = true;
        ...
    }
```

**Comment by sprajcpf** [comment]
We observe the same situation here. However, we will check first, that the application is not leaking any connections.

**Comment by sprajcpf** [comment]
We now added the following settings: 

debugUnreturnedConnectionStackTraces=true
unreturnedConnectionTimeout=30

1) We do not see any log output related to that
2) There size of the connection pool still stays way under maxConnections.
3) We still see blocking threads for 10-30s in this stack:

qtp2123178498-258  Blocked CPU usage on sample: 0ms
  java.lang.Object.wait(long)
  com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(long)
  com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(long)
  com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(long)
  com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse()
  com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection()
  com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection()
  org.hibernate.connection.C3P0ConnectionProvider.getConnection()
  org.hibernate.jdbc.ConnectionManager.openConnection()
  org.hibernate.jdbc.ConnectionManager.getConnection()
  org.hibernate.jdbc.JDBCContext.connection()
  org.hibernate.transaction.JDBCTransaction.begin()
  org.hibernate.impl.SessionImpl.beginTransaction()
  sun.reflect.GeneratedMethodAccessor54.invoke(Object, Object[])
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Object, Object[])
  java.lang.reflect.Method.invoke(Object, Object[])
  org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(Object, Method, Object[])
  com.sun.proxy.$Proxy59.beginTransaction()

and

INFO   | jvm 1    | 2019/01/30 12:15:23 | Caused by: java.sql.SQLException: An attempt by a client to checkout a Connection has timed out.
INFO   | jvm 1    | 2019/01/30 12:15:23 | 	at com.mchange.v2.sql.SqlUtils.toSQLException(Unknown Source)
INFO   | jvm 1    | 2019/01/30 12:15:23 | 	at com.mchange.v2.sql.SqlUtils.toSQLException(Unknown Source)
INFO   | jvm 1    | 2019/01/30 12:15:23 | 	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(Unknown Source)
INFO   | jvm 1    | 2019/01/30 12:15:23 | 	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(Unknown Source)
INFO   | jvm 1    | 2019/01/30 12:15:23 | 	at org.hibernate.connection.C3P0ConnectionProvider.getConnection(Unknown Source)
INFO   | jvm 1    | 2019/01/30 12:15:23 | 	... 27 more
INFO   | jvm 1    | 2019/01/30 12:15:23 | Caused by: com.mchange.v2.resourcepool.TimeoutException: A client timed out while waiting to acquire a resource from com.mchange.v2.resourcepool.BasicResourcePool@e9aeced -- timeout at awaitAvailable()
INFO   | jvm 1    | 2019/01/30 12:15:23 | 	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(Unknown Source)
INFO   | jvm 1    | 2019/01/30 12:15:23 | 	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(Unknown Source)
INFO   | jvm 1    | 2019/01/30 12:15:23 | 	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(Unknown Source)
INFO   | jvm 1    | 2019/01/30 12:15:23 | 	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(Unknown Source)
INFO   | jvm 1    | 2019/01/30 12:15:23 | 	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(Unknown Source)
INFO   | jvm 1    | 2019/01/30 12:15:23 | 	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(Unknown Source)
INFO   | jvm 1    | 2019/01/30 12:15:23 | 	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(Unknown Source)
INFO   | jvm 1    | 2019/01/30 12:15:23 | 	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(Unknown Source)
INFO   | jvm 1    | 2019/01/30 12:15:23 | 	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(Unknown Source)
INFO   | jvm 1    | 2019/01/30 12:15:23 | 	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(Unknown Source)
INFO   | jvm 1    | 2019/01/30 12:15:23 | 	... 30 more
INFO   | jvm 1    | 2019/01/30 12:15:23 | 
INFO   | jvm 1    | 2019/01/30 12:15:23 | [12:15:23] SEVERE [WrappedRunnable]: Database connection problem: Cannot open connection
