### ISSUE TITLE
c3p0 with jaybird

### ISSUE THREAD

**Issue by philippscs** [swaldman/c3p0#128]
I try to use c3p0 with jaybird to connect to a firebird database.

Therefore I'm using the DataSource class [FBSimpleDataSource](https://github.com/FirebirdSQL/jaybird/blob/master/src/main/org/firebirdsql/ds/FBSimpleDataSource.java).

When calling c3p0 for a pooled DataSource with
``` java
DataSources.pooledDataSource(firebirdDataSource, poolProperties)
```

the following exception is logged to the console:

```
javax.management.IntrospectionException: getter and setter cannot both be null
	at javax.management.MBeanAttributeInfo.attributeType(MBeanAttributeInfo.java:347) ~[?:1.8.0_191]
	at javax.management.MBeanAttributeInfo.<init>(MBeanAttributeInfo.java:185) ~[?:1.8.0_191]
	at com.mchange.v2.c3p0.management.DynamicPooledDataSourceManagerMBean.extractAttributeInfos(DynamicPooledDataSourceManagerMBean.java:603) [c3p0-0.9.5.2.jar:0.9.5.2]
	at com.mchange.v2.c3p0.management.DynamicPooledDataSourceManagerMBean.reinitialize(DynamicPooledDataSourceManagerMBean.java:205) [c3p0-0.9.5.2.jar:0.9.5.2]
	at com.mchange.v2.c3p0.management.DynamicPooledDataSourceManagerMBean.access$000(DynamicPooledDataSourceManagerMBean.java:76) [c3p0-0.9.5.2.jar:0.9.5.2]
	at com.mchange.v2.c3p0.management.DynamicPooledDataSourceManagerMBean$1.propertyChange(DynamicPooledDataSourceManagerMBean.java:155) [c3p0-0.9.5.2.jar:0.9.5.2]
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335) [?:1.8.0_191]
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327) [?:1.8.0_191]
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263) [?:1.8.0_191]
	at com.mchange.v2.c3p0.impl.PoolBackedDataSourceBase.setConnectionPoolDataSource(PoolBackedDataSourceBase.java:70) [c3p0-0.9.5.2.jar:0.9.5.2]
	at com.mchange.v2.c3p0.DataSources.pooledDataSource(DataSources.java:281) [c3p0-0.9.5.2.jar:0.9.5.2]
	at com.mchange.v2.c3p0.DataSources.pooledDataSource(DataSources.java:262) [c3p0-0.9.5.2.jar:0.9.5.2]
	at firebird.FirebirdDataSourceConfig.dataSource(FirebirdDataSourceConfig.java:50) [classes/:?]
	at firebird.FirebirdDataSourceConfig$$EnhancerBySpringCGLIB$$69e2735a.CGLIB$dataSource$0(<generated>) [classes/:?]
	at firebird.FirebirdDataSourceConfig$$EnhancerBySpringCGLIB$$69e2735a$$FastClassBySpringCGLIB$$a750e49c.invoke(<generated>) [classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) [spring-core-4.3.21.RELEASE.jar:4.3.21.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) [spring-context-4.3.21.RELEASE.jar:4.3.21.RELEASE]
	at firebird.FirebirdDataSourceConfig$$EnhancerBySpringCGLIB$$69e2735a.dataSource(<generated>) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) [spring-beans-4.3.21.RELEASE.jar:4.3.21.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) [spring-beans-4.3.21.RELEASE.jar:4.3.21.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1178) [spring-beans-4.3.21.RELEASE.jar:4.3.21.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1072) [spring-beans-4.3.21.RELEASE.jar:4.3.21.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511) [spring-beans-4.3.21.RELEASE.jar:4.3.21.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481) [spring-beans-4.3.21.RELEASE.jar:4.3.21.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312) [spring-beans-4.3.21.RELEASE.jar:4.3.21.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.3.21.RELEASE.jar:4.3.21.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308) [spring-beans-4.3.21.RELEASE.jar:4.3.21.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.3.21.RELEASE.jar:4.3.21.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) [spring-beans-4.3.21.RELEASE.jar:4.3.21.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) [spring-context-4.3.21.RELEASE.jar:4.3.21.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) [spring-context-4.3.21.RELEASE.jar:4.3.21.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.18.RELEASE.jar:1.5.18.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.18.RELEASE.jar:1.5.18.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.18.RELEASE.jar:1.5.18.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.18.RELEASE.jar:1.5.18.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.18.RELEASE.jar:1.5.18.RELEASE]
```

Apart from the log entry, everything works fine with the DataSource. 

Any idea what is wrong and how this log message can be avoided?

**Comment by swaldman** [comment]
Fixed, I hope.

https://github.com/swaldman/c3p0/commit/028682f30e057306eaee3bd4d708a67a2ffc1f60

Thanks!
