### ISSUE TITLE
c3P0 checkConnectionsOnCheckOut - How it works?

### ISSUE THREAD

**Issue by PardalDev** [swaldman/c3p0#150]
Dear all, 

We are using an implementation of c3p0 pool based db connection, and we noticed that after some long period of time, those connections get broken, because a firewall configuration issue or maybe a DB idle connection parameter. Any way, we are trying to figure how checkConnectionsOnCheckOut  actually works. 

Our connection pool was defined like this:

<c3p0-config>

        <default-config>
                
                <property name="checkoutTimeout">10000</property>
                <property name="idleConnectionTestPeriod">60</property>
                <property name="PreferredTestQuery">SELECT 1 FROM DUAL</property>
                <property name="acquireRetryAttempts">5</property>
                <property name="acquireRetryDelay">60000</property>
                <property name="breakAfterAcquireFailure">false</property>
                <property name="debugUnreturnedConnectionStackTraces">true</property>
                <property name="unreturnedConnectionTimeout">0</property>
                
                <property name="maxConnectionAge">3600</property>
                <property name="testConnectionOnCheckout">true</property>

                
                <property name="numHelperThreads">15</property>
        </default-config>
		
		<named-config name="mts_historic">
                <property name="minPoolSize">50</property>
                <property name="initialPoolSize">50</property>
                <property name="maxPoolSize">50</property>
                <property name="acquireIncrement">50</property>
                <property name="connectionCustomizerClassName">us.inswitch.jextdb.database.MTSConnectionCustomizer</property>
                <property name="jdbcUrl">jdbc:oracle:thin:@(DESCRIPTION_LIST= (DESCRIPTION= (ADDRESS = (PROTOCOL = TCP)(HOST =XXXXXXXX)(PORT =1521)) (CONNECT_DATA= (SERVICE_NAME= XXXXXXX))))</property>
                <property name="driverClass">oracle.jdbc.driver.OracleDriver</property>
                <property name="user">XXXXXX</property>
                <property name="password">UQsdKzKfo9wwy0/HnGR50g==</property>
		</named-config>
</c3p0-config>

So, by using this configuration, we have noticed that the connection testing always succeed, no one of the connections are marked as failed or boken. But, after a long period of time (for example during morning) of inactivity when we try to use a connection, it is being checked by the parameter testConnectionOnCheckout and it fails but the query also fails.

1) The testConnectionOnCheckout  is an internal connection testing from DB pool? It and should be transparent for the clients?

2) It triggers a new connection? The desision of a new connection depends on something else?

3) If the c3p0 connection is restablished in an automatic way after the testConnectionOnCheckout  failure, the issue that we are currently facing could be related to the aquire increment that we are using? (we are using an static pool max = min = acuireIncrement)

Thanks you in advance.

Kind regards.
Luis

**Comment by fschiettecatte** [comment]
Luis

I notice that ‘PreferredTestQuery’ has an initial capital, should that be ‘preferredTestQuery’?

And do you know if 'SELECT 1 FROM DUAL’ is making it to the server ?

 François

**Comment by marcolopes** [comment]
I'm having the same problem with DEFAULT configurations!

Using:
- mysql-connector-java-**5.1.49**.jar
- c3p0-**0.11.2**.jar
- Java 8

C3P0 **config**:
```
pool.setJdbcUrl(url);
pool.setUser(user);
pool.setPassword(password);
pool.setTestConnectionOnCheckout(true);
```

Still, after a period of inactivity, the MySQL connection returned from the pool is invalid!

I get a NEW connection in every database method, to ensure that the pool does the underlying job.

Any ideas why?

This is the error LOG from the app:

```
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 44.587.068 milliseconds ago.  The last packet sent successfully to the server was 44.587.069 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
jul 23 14:54:19 dev-server services[811]:         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
jul 23 14:54:19 dev-server services[811]:         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
jul 23 14:54:19 dev-server services[811]:         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
jul 23 14:54:19 dev-server services[811]:         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
jul 23 14:54:19 dev-server services[811]:         at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
jul 23 14:54:19 dev-server services[811]:         at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
jul 23 14:54:19 dev-server services[811]:         at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3706)
jul 23 14:54:19 dev-server services[811]:         at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2506)
jul 23 14:54:19 dev-server services[811]:         at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
jul 23 14:54:19 dev-server services[811]:         at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
jul 23 14:54:19 dev-server services[811]:         at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4776)
jul 23 14:54:19 dev-server services[811]:         ... 6 more
jul 23 14:54:19 dev-server services[811]: Caused by: java.net.SocketException: Túnel quebrado (Write failed)
jul 23 14:54:19 dev-server services[811]:         at java.net.SocketOutputStream.socketWrite0(Native Method)
jul 23 14:54:19 dev-server services[811]:         at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
jul 23 14:54:19 dev-server services[811]:         at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
jul 23 14:54:19 dev-server services[811]:         at sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:341)
jul 23 14:54:19 dev-server services[811]:         at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1106)
jul 23 14:54:19 dev-server services[811]:         at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
jul 23 14:54:19 dev-server services[811]:         at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
jul 23 14:54:19 dev-server services[811]:         at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3688)
```

**Comment by fschiettecatte** [comment]
Looking at your log, it feels like MySQL is dropping the connection on the pool.

I have a few suggestions, apologies if they appear obvious, or if you have already looked into that

There is a difference between database connections and pool connections. Your app gets a connection from the pool, the pool in turn allocates an existing database connection or creates a new one. Once you are done with the connection and return it to the pool it is ready to be reallocated. It is up to the pool to keep that connection alive by pinging the database or closing the connection and creating a new one. In turn the database may drop the connection, and the pools connection is now broken.

I've only used myBatis with c3p0 and mysql so what follows if good only for that, but is a useful guide for tracking this down.

In MySQL I have 'wait_timeout' set to 3600 seconds in my.cnf, basically a connection will be dropped if idle for more than. If you can't check my.cnf just connect to MySQL with a command line tool and run "SHOW VARIABLES LIKE 'wait_timeout';".

In c3p0 I have 'maxIdleTime' set to 3500 seconds (less than MySQL), and 'preferredTestQuery' set to "/* ping */ SELECT 1" because it is converted into a [PING by Connector/J](https://dev.mysql.com/doc/connector-j/en/connector-j-usagenotes-j2ee-concepts-connection-pooling.html).

**Comment by marcolopes** [comment]
> Looking at your log, it feels like MySQL is dropping the connection on the pool.

But the poolmanager should validate the connection before returning it to the client! I don't think i should mess with any other configs other than signaling the pool that the connection should be validated on "request".

**I'm not "closing" the connection after getting it from the pool and I'm done with it...** i believe the best practice is to CLOSE it (because it's a pooled connection, the pool will know what to do with it).

Could this be the problem?

**Comment by fschiettecatte** [comment]
I apologize for the incorrect terminology, connections are returned to the pool, not closed. MyBatis handles that for me, all I need to do is create a session.

From what I can tell [c3po does *not* validate connections on check-in or check-out by default](MyBatis.getSqlSession), and you will need to set [preferredTestQuery](https://www.mchange.com/projects/c3p0/#preferredTestQuery) too.

**Comment by marcolopes** [comment]
> From what I can tell [c3po does _not_ validate connections on check-in or check-out by default](MyBatis.getSqlSession)

I understand! That's why i use the **setTestConnectionOnCheckout**(true)!

> and you will need to set [preferredTestQuery](https://www.mchange.com/projects/c3p0/#preferredTestQuery) too.

That's NOT entirely true!!! Take a look at the docs!

https://www.mchange.com/projects/c3p0/#legacy_configuring_connection_testing

> When configuring Connection testing, first try to minimize the cost of each test. **If you are using a JDBC driver that you are certain supports the new(ish) jdbc4 API — and if you are using c3p0-0.9.5 or higher! — let your driver handle this for you**. jdbc4 Connections include a method called isValid() that should be implemented as a fast, reliable Connection test. By default, c3p0 will use that method if it is present.

https://www.mchange.com/projects/c3p0/#preferredTestQuery

> Default: null
> Defines the query that will be executed for all connection tests, if the default ConnectionTester (or some other implementation of [QueryConnectionTester](https://www.mchange.com/projects/c3p0/apidocs/com/mchange/v2/c3p0/QueryConnectionTester.html), or better yet [FullQueryConnectionTester](https://www.mchange.com/projects/c3p0/apidocs/com/mchange/v2/c3p0/FullQueryConnectionTester.html)) is being used. [See ["Configuring Connection Testing"](https://www.mchange.com/projects/c3p0/#configuring_connection_testing)]
> 
> **This is rarely useful, and should be left as null except when using very old (pre Java 6) or broken JDBC drivers**. **More recent drivers define a Connection.isValid(int timeout) method for efficient Connection tests**, which will be used unless this parameter, automaticTestTable, and/or connectionTesterClassName are set to nondefault values. When working with very old JDBC drivers (or drivers who Connection.isValid(...) method is poorly implemented), defining a preferredTestQuery that will execute quickly in your database may dramatically speed up Connection tests.

Bottom line: One does not need to initialize **preferredTestQuery** to ensure that **setTestConnectionOnCheckout**(true) is honored!

**Comment by swaldman** [comment]
`setTestConnectionOnCheckout(true)` should always be honored, one way or another (unless you actively work to sabotage it by configuring a bad `preferredTestQuery` or something). it will just be very slow if `Connection.isValid(timeout)` is unavailable, unless you set a faster `preferredTestQuery` or `automaticTestTable`.

You should be calling `close()` on your `Connection` immediately after use. `c3p0` intercepts the close, and returns the physical `Connection` to the pool. If at an application level you are holding `Connections` for long periods of time, those Connections will time out, and c3p0 won't have anything it can do about it.

Just-checked-out Connections should not throw Exceptions due to timing out out when `testConnectionOnCheckout` is `true`. A call to `Connection.isValid(timeout)` hopefully resents any DBMS/driver-level timeout period. (If it does not, there is a race condition, a Connection might test valid then timeout very soon after checkout, while it is still in use.)

I'd try to verify Connection testing is working as you think. `c3p0` dumps its config at INFO on initialization, check that dump and make sure `testConnectionOnCheckout` is `true`. Then try setting the logger `com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool` to `FINEST` or `TRACE` and you should see the Connection tests in your logs.

**Comment by marcolopes** [comment]
> You should be calling `close()` on your `Connection` immediately after use. `c3p0` intercepts the close, and returns the physical `Connection` to the pool. If at an application level you are holding `Connections` for long periods of time, those Connections will time out, and c3p0 won't have anything it can do about it.

So, this could be the cause!

I've already changed the code and will test soon.

**Comment by marcolopes** [comment]
Closing the connections works "better", YET, sometimes i get com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: **No operations allowed after connection closed**.

I give up. This should NOT happen with C3P0 using **setTestConnectionOnCheckout(true)**

Switching back to **DBCP** to give it another try (with the code now closing the connections)

**Comment by marcolopes** [comment]
Same problem with DBCP!

Out of ideas :\\\

**Comment by swaldman** [comment]
In what context do you see `com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed`? Does it break your transactions, or os it just something you are seeing in the logs? (Maybe include the stack trace.)

**Comment by marcolopes** [comment]
> In what context do you see `com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed`? Does it break your transactions, or os it just something you are seeing in the logs? (Maybe include the stack trace.)

After another debug session, it seems this is due to CONCURRENCY problems!

This is a web server app using JETTY in the API side, that makes several calls at the database methods (so, in some scenarios, the SAME connection is returned by the pool and one of the operations fails after the first method closes the connection)

**Comment by swaldman** [comment]
Every Connection returned by the pool will be distinct, and the pool is made for concurrency.

It sounds like different threads (requests / session) of your application share a `Connection` after database checkout. Just don't! The whole point of a pool is for application developers not to be clever. At the very moment you need the database, call `dataSource.getConnection()`. The database Connection should usually never be assigned to anything other than a local variable inside of functions. No member variable or static variable should ever refer to it. Call `dataSource.getConnection()` inside your function, do one unit of work, then call `close()` on the `Connection`.

(Ideally you don't even explicitly call `close()`. Ideally you acquire the `Connection` in a [try-with-resources block](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html). Otherwise you should use an explicit `finally` block, which requires more care than developers typically manage in order to get right.)

**Comment by marcolopes** [comment]
Database methods are now synchronized (so, no more concurrent accesses).

Still getting an "invalid" connection after a "long" inactivity time (i configured MySQL to timeout after 60 seconds for testing, but the problems occur after several hours - it's strange!)

Anyway, shouldn't C3P0 **TestConnectionOnCheckout** avoid this problem? This should not be a VALID connection! More debug ahead (I'm going to implement a "manual" connection.isValid(1) check after getting the connection from the pool, just to be sure that the connection is INVALID in this scenario)

```
Aug 01 10:34:24 dev-server services[809]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 29,598,953 milliseconds ago.  The last packet sent successfully to the server was 29,598,957 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
Aug 01 10:34:24 dev-server services[809]:         at sun.reflect.GeneratedConstructorAccessor135.newInstance(Unknown Source)
Aug 01 10:34:24 dev-server services[809]:         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
Aug 01 10:34:24 dev-server services[809]:         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
Aug 01 10:34:24 dev-server services[809]:         at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
Aug 01 10:34:24 dev-server services[809]:         at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
Aug 01 10:34:24 dev-server services[809]:         at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3706)
Aug 01 10:34:24 dev-server services[809]:         at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2506)
Aug 01 10:34:24 dev-server services[809]:         at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
Aug 01 10:34:24 dev-server services[809]:         at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
Aug 01 10:34:24 dev-server services[809]:         at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4776)
Aug 01 10:34:24 dev-server services[809]:         at org.projectocolibri.web.api.database.DatabaseParameters.getConnection(DatabaseParameters.java:26)
Aug 01 10:34:24 dev-server services[809]:         at org.projectocolibri.web.api.database.manager.AbstractManager.getConnection(AbstractManager.java:72)
Aug 01 10:34:24 dev-server services[809]:         ... 6 more
Aug 01 10:34:24 dev-server services[809]: Caused by: java.net.SocketException: Broken pipe (Write failed)
Aug 01 10:34:24 dev-server services[809]:         at java.net.SocketOutputStream.socketWrite0(Native Method)
Aug 01 10:34:24 dev-server services[809]:         at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
Aug 01 10:34:24 dev-server services[809]:         at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
Aug 01 10:34:24 dev-server services[809]:         at sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:341)
Aug 01 10:34:24 dev-server services[809]:         at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1106)
Aug 01 10:34:24 dev-server services[809]:         at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
Aug 01 10:34:24 dev-server services[809]:         at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
Aug 01 10:34:24 dev-server services[809]:         at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3688)
Aug 01 10:34:24 dev-server services[809]:         ... 12 more
```
