### ISSUE TITLE
C3p0 Error

### ISSUE THREAD

**Issue by KesavaTankasala** [swaldman/c3p0#161]
Hi All 

I AM facing This issue in connection side, please share the solutions to come out of this
![IMG-20220317-WA0007](https://user-images.githubusercontent.com/101802583/158793224-b6fd5a84-c6d8-4ae2-a815-4f3981b60bcd.jpg)

**Comment by KesavaTankasala** [comment]
Pasted error for better view.


 ] Executor: Type: A: C: NewPooledConnection:223 - [c3p0] Another error has occurred [ java.sql.SQLException: Invalid state, the Connection object is closed. ] which will not be reported to listeners!
java.sql.SQLException: Invalid state, the Connection object is closed.
        at net.sourceforge.jtds.jdbc.JtdsConnection.checkOpen(JtdsConnection.java:1744)
        at net.sourceforge.jtds.jdbc.JtdsConnection.getWarnings(JtdsConnection.java:2356)
        at com.mchange.v2.c3p0.impl.NewProxyConnection.getWarnings(NewProxyConnection.java:933)
        at org.hibernate.util.JDBCExceptionReporter.logAndClearWarnings(JDBCExceptionReporter.java:22)
        at org.hibernate.jdbc.ConnectionManager.closeConnection(ConnectionManager.java:325)
        at org.hibernate.jdbc.ConnectionManager.cleanup(ConnectionManager.java:262)
        at org.hibernate.jdbc.ConnectionManager.close(ConnectionManager.java:194)
        at org.hibernate.impl.SessionImpl.close(SessionImpl.java:289)
        at com.business.sem.base._BaseRootDAO.closeCurrentSession(_BaseRootDAO.java:159)
        at com.business.sem.h3.BaseDatastore.close(BaseDatastore.java:156)
        at com.business.sem.util.Utils.closeQuietly(Utils.java:52)
        at com.business.sem.reportscheduler.VendorReportQueueRunnable.runReports(VendorReportQueueRunnable.java:93)
        at com.business.sem.reportscheduler.VendorReportQueueRunnable.run(VendorReportQueueRunnable.java:46)
        at java.lang.Thread.run(Thread.java:748)
2022-03-14 21:57:38,953  WARN [C3P0PooledConnectionPoolManager[identityToken->161okg4an12ikmmhlm1sx3|640cb5d4]-HelperThread-#0] Executor: Type: A: C: StatementUtils:223 - Statement close FAILED.
java.sql.SQLException: Invalid state, the Connection object is closed.
        at net.sourceforge.jtds.jdbc.TdsCore.checkOpen(TdsCore.java:481)
        at net.sourceforge.jtds.jdbc.TdsCore.clearResponseQueue(TdsCore.java:767)
        at net.sourceforge.jtds.jdbc.JtdsStatement.reset(JtdsStatement.java:722)
        at net.sourceforge.jtds.jdbc.JtdsStatement.close(JtdsStatement.java:966)
        at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.close(JtdsPreparedStatement.java:707)
        at com.mchange.v1.db.sql.StatementUtils.attemptClose(StatementUtils.java:53)
        at com.mchange.v2.c3p0.stmt.GooGooStatementCache$StatementDestructionManager.synchronousDestroyStatement(GooGooStatementCache.java:943)
        at com.mchange.v2.c3p0.stmt.GooGooStatementCache.closeAll(GooGooStatementCache.java:387)
        at com.mchange.v2.c3p0.impl.NewPooledConnection.closeAllCachedStatements(NewPooledConnection.java:781)
        at com.mchange.v2.c3p0.impl.NewPooledConnection.close(NewPooledConnection.java:622)
        at com.mchange.v2.c3p0.impl.NewPooledConnection.closeMaybeCheckedOut(NewPooledConnection.java:255)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.destroyResource(C3P0PooledConnectionPool.java:622)
        at com.mchange.v2.resourcepool.BasicResourcePool$1DestroyResourceTask.run(BasicResourcePool.java:1076)
        at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
