### ISSUE TITLE
mchange.v2.c3p0.impl.NewPooledConnection - [c3p0]  The following Exceptions occurred while trying to clean up a Connection's stranded resource

### ISSUE THREAD

**Issue by jsusanto** [swaldman/c3p0#169]
Hi Team,

I'm using c3p0 version: 0.9.5

I keep getting the following INFO exception.

========================================================================
INFO com.mchange.v2.c3p0.impl.NewPooledConnection - [c3p0] 
The following Exceptions occurred while trying to clean up a Connection's stranded resources:

INFO com.mchange.v2.c3p0.impl.NewPooledConnection - 
[c3p0 -- conection resource close Exception] java.sql.SQLException: JZ006: 
Caught IOException: java.io.IOException: JZ0EM: End of data. at com.sybase.jdbc4.jdbc.ErrorMessage.
raiseError(Unknown Source) ~[jConnect-7.0.jar:?] at com.sybase.jdbc4.jdbc.ErrorMessage.
raiseErrorCheckDead(Unknown Source) ~[jConnect-7.0.jar:?] at com.sybase.jdbc4.tds.
TdsResultSet.next(Unknown Source) ~[jConnect-7.0.jar:?] at com.sybase.jdbc4.tds.
TdsResultSet.close(Unknown Source) ~[jConnect-7.0.jar:?] at com.sybase.jdbc4.
jdbc.SybResultSet.markDead(Unknown Source) ~[jConnect-7.0.jar:?] 
at com.sybase.jdbc4.jdbc.SybResultSet.close(Unknown Source) ~[jConnect-7.0.jar:?] 2
at com.sybase.jdbc4.jdbc.SybResultSet.close(Unknown Source) ~[jConnect-7.0.jar:?] at

========================================================================

Below is the current configuration.

<bean id="XXX" class="com.mchange.v2.c3p0.ComboPooledDataSource" destroy-method="close">
        <property name="driverClass"                          value="com.sybase.jdbc4.jdbc.SybDriver" />
        <property name="acquireIncrement"                     value="5"/>
        <property name="acquireRetryAttempts"                 value="30"/>
        <property name="acquireRetryDelay"                    value="1000"/>
        <property name="autoCommitOnClose"                    value="false"/>
        <property name="automaticTestTable"                   value="NULL"/>
        <property name="breakAfterAcquireFailure"             value="false"/>
        <property name="checkoutTimeout"                      value="60000"/>
        <property name="connectionCustomizerClassName"        value="NULL"/>
        <property name="debugUnreturnedConnectionStackTraces" value="false"/>
        <property name="factoryClassLocation"                 value="NULL"/>
        <property name="forceIgnoreUnresolvedTransactions"    value="false"/>
        <property name="idleConnectionTestPeriod"             value="60"/>
        <property name="initialPoolSize"                      value="10"/>
        <property name="maxAdministrativeTaskTime"            value="0"/>
        <property name="maxConnectionAge"                     value="0"/>
        <property name="maxIdleTime"                          value="1800"/>
        <property name="maxIdleTimeExcessConnections"         value="60"/>
        <property name="maxPoolSize"                          value="5"/>
        <property name="maxStatements"                        value="0" />
        <property name="maxStatementsPerConnection"           value="0"/>
        <property name="minPoolSize"                          value="10"/>
        <property name="numHelperThreads"                     value="25"/>
        <property name="overrideDefaultUser"                  value="NULL"/>
        <property name="overrideDefaultPassword"              value="NULL"/>
        <property name="preferredTestQuery"                   value="SELECT 1"/>
        <property name="propertyCycle"                        value="5"/>
        <property name="testConnectionOnCheckin"              value="false"/>
        <property name="testConnectionOnCheckout"             value="false"/>
        <property name="unreturnedConnectionTimeout"          value="0"/>
        <property name="usesTraditionalReflectiveProxies"     value="false"/>
    </bean>

By any chance, do you know why I keep getting this INFO exception? how to resolve this issue?

Many thanks,

**Comment by swaldman** [comment]
When you close (really check in) a Connection, c3p0 tries to clean up any Statements or ResultSets that clients did not close, before making the Connection available again in the pool. Ideally, there should be no such stranded resources, because clients should use [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) when working with Statements and ResultSets. But that is not always the case.

In this case, a client failed to clean up a ResultSet, c3p0 tried to clean that up (ie close()) that prior to making it available from the pool, but an Exception occurred when calling that close()

The best way to avoid this kind of thing is to take care to close() your Statements and ResultSets.
