### ISSUE TITLE
BasicResourcePool.this.unused.add(0, resc);  NullPointerException

### ISSUE THREAD

**Issue by xtb359** [swaldman/c3p0#182]
[ThreadPoolAsynchronousRunner] {} (C3P0PooledConnectionPoolManager[identityToken->z8kfltb7l920rj9a0cyd|6b3c1f17]-HelperThread-#2) Thread[C3P0PooledConnectionPoolManager[identityToken->z8kfltb7l920rj9a0cyd|6b3c1f17]-HelperThread-#2,5,main] -- caught unexpected Exception while executing posted task.
java.lang.NullPointerException: null
	at java.util.LinkedList.linkBefore(LinkedList.java:157) ~[?:1.8.0_202]
	at java.util.LinkedList.add(LinkedList.java:512) ~[?:1.8.0_202]
	at com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask.run(BasicResourcePool.java:1385) ~[c3p0-0.9.5.2.jar:0.9.5.2]
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696) [mchange-commons-java-0.2.15.jar:0.2.15]

Why did this error occur and how can it be resolved？

**Comment by xtb359** [comment]
The server architecture is aarch64， The c3p0 version is 0.9.5.2

**Comment by swaldman** [comment]
(hi. sorry for the delayed response. 0.9.5.2 is a very, very old version of c3p0. i'd first try upgrading to a more recent version.)

**Comment by swaldman** [comment]
Hi again!

I think this commit should address the problem, will be part of c3p0-0.11.0.

https://github.com/swaldman/c3p0/commit/f7919b6048d4cd5ef469ea87b656b097b512ffb6

**Comment by swaldman** [comment]
(Thanks for the report!)
