### ISSUE TITLE
"A client timed out while waiting to acquire a resource from com.mchange.v2.resourcepool.BasicResourcePool@f03f0af -- timeout at awaitAvailable()"

### ISSUE THREAD

**Issue by tazmaniax** [swaldman/c3p0#20]
I'm running a Java Play v1.3.x app using MySQL Connector/J v5.1.29 on Heroku that connects to an AWS RDS MySQL Tiny instance within the same availability zone (us-east-1). I continually see a connection timeouts as below when starting up the application. The checkout timeout has been 5sec (the default) but which I've now increased to 7sec. I wouldn't expect it to take more than 5sec to acquire a connection within the same availability zone. I'm not sure if this is an AWS issue, a Heroku issue or a c3p0 issues or a combination. I just want to check that this can be resolved by simply increasing the checkout timeout value or there could possibly be another issue. Thanks, Chris.

```
02-03-14 02:33:21,661 [main] ERROR play
Cannot connected to the database : An attempt by a client to checkout a Connection has timed out.
java.sql.SQLException: An attempt by a client to checkout a Connection has timed out.
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
        at play.db.DBPlugin.onApplicationStart(DBPlugin.java:147)
        at play.plugins.PluginCollection.onApplicationStart(PluginCollection.java:525)
        at play.Play.start(Play.java:537)
        at play.Play.init(Play.java:309)
        at play.server.Server.main(Server.java:166)
Caused by: com.mchange.v2.resourcepool.TimeoutException: A client timed out while waiting to acquire a resource from com.mchange.v2.resourcepool.BasicResourcePool@f03f0af -- timeout at awaitAvailable()
        at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1416)
        at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:606)
        at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:526)
        ... 5 more
```

**Comment by durga1791** [comment]
swaldman@ 
I am also getting the same error. I observer that when call is reaching to number of MaxPoolSize then it is getting same error  i have following configuration 
idleConnectionTestPeriod=60;
     initialPoolSize=2;
     minPoolSize=2;
     maxIdleTime=100;
     maxPoolSize=10;
when 10th request call is coming then  producing error "error timeout at awaitAvailable()". Can you please help to resolve

**Comment by swaldman** [comment]
@durga1791 building to maxPoolSize then hanging (or timing out with an error if `checkoutTimeout` is set) is very likely a Connection leak. (You almost certainly have `checkoutTimeout` set given the error you are seeing, the config you show above is not complete, or there are things affecting c3p0's configuration that you don't know about.)

Please see [the docs](http://www.mchange.com/projects/c3p0/#configuring_to_debug_and_workaround_broken_clients) for debugging or working around Connection leaks.

**Comment by durga1791** [comment]
HI swaldman,

I found below are also configured.
c3p0.maxStatementsPerConnection=50
# milliseconds
c3p0.checkoutTimeout=60000

# Other Settings

c3p0.debugUnreturnedConnectionStackTraces=true
c3p0.maxIdleTimeExcessConnections=600
c3p0.preferredTestQuery=SELECT 1 FROM DUAL
c3p0.unreturnedConnectionTimeout=1800


when commenting this c3p0.checkoutTimeout=60000, it is taking default value
then connection is waiting indefinitely.


Regards
Durga

**Comment by JanakiramanChandrasekran** [comment]
@swaldman @durga1791 Am also facing similar issue.. Can you share the solution if you have fix identified ?

**Comment by sprajcpf** [comment]
Maybe this is related to #120 ?

**Comment by JanakiramanChandrasekran** [comment]
I fixed the issue..

**Comment by sprajcpf** [comment]
> I fixed the issue..

How?

**Comment by JanakiramanChandrasekran** [comment]
The issue was bubbled up when SSL/ TLS is enabled... So, as suggested here.. I increased the time out to 30 secs & max connections to 10..

**Comment by tranthanhdeveloper** [comment]
I got the same issue when I set the **maxPoolSize=0**.  Anyone who is facing this problem can consider this mistake.

**Comment by ldanny19** [comment]
> The issue was bubbled up when SSL/ TLS is enabled... So, as suggested here.. I increased the time out to 30 secs & max connections to 10..

Puedes poner la config final de C3p0 y el SSL estaba activo en el server de aplicacion?
