### ISSUE TITLE
A lot of FileNotFoundException stacktraces in c3p0 log

### ISSUE THREAD

**Issue by borislubimov** [swaldman/c3p0#52]
I configure c3p0 through java so I don't have any .properties files for c3p0. Therefore I have a lot of FileNotFoundException stacktraces in c3p0 log (several time for each .properties file) They all on debug level but still do we need all that stacktraces in the lines which tell us about absence of that files?

With all that stacktraces log looks not very pretty:

15:22:43 MLog-Init-Reporter DEBUG (Slf4jMLog.java#log:198): The configuration file for resource identifier '/mchange-commons.properties' could not be found. Skipping.
java.io.FileNotFoundException: Resource not found at path '/mchange-commons.properties'.
	at com.mchange.v2.cfg.BasicPropertiesConfigSource.propertiesFromSource(BasicPropertiesConfigSource.java:64)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.firstInit(BasicMultiPropertiesConfig.java:185)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.<init>(BasicMultiPropertiesConfig.java:110)
	at com.mchange.v2.cfg.ConfigUtils.read(ConfigUtils.java:63)
	at com.mchange.v2.cfg.ConfigUtils.readVmConfig(ConfigUtils.java:115)
	at com.mchange.v2.cfg.MLogConfigSource.readVmConfig(MLogConfigSource.java:46)
	at com.mchange.v2.log.MLogConfig.refresh(MLogConfig.java:59)
	at com.mchange.v2.log.MLog.refreshConfig(MLog.java:59)
	at com.mchange.v2.log.MLog.<clinit>(MLog.java:51)
	at com.mchange.v2.naming.JavaBeanReferenceMaker.<clinit>(JavaBeanReferenceMaker.java:51)
	at com.mchange.v2.c3p0.impl.PoolBackedDataSourceBase.<clinit>(PoolBackedDataSourceBase.java:263)
...
15:22:43 MLog-Init-Reporter DEBUG (Slf4jMLog.java#log:198): The configuration file for resource identifier '/c3p0.properties' could not be found. Skipping.
java.io.FileNotFoundException: Resource not found at path '/c3p0.properties'.
	at com.mchange.v2.cfg.BasicPropertiesConfigSource.propertiesFromSource(BasicPropertiesConfigSource.java:64)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.firstInit(BasicMultiPropertiesConfig.java:185)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.<init>(BasicMultiPropertiesConfig.java:110)
	at com.mchange.v2.cfg.ConfigUtils.read(ConfigUtils.java:63)
	at com.mchange.v2.cfg.ConfigUtils.readVmConfig(ConfigUtils.java:115)
	at com.mchange.v2.cfg.MLogConfigSource.readVmConfig(MLogConfigSource.java:46)
	at com.mchange.v2.log.MLogConfig.refresh(MLogConfig.java:59)
	at com.mchange.v2.log.MLog.refreshConfig(MLog.java:59)
	at com.mchange.v2.log.MLog.<clinit>(MLog.java:51)
	at com.mchange.v2.naming.JavaBeanReferenceMaker.<clinit>(JavaBeanReferenceMaker.java:51)
	at com.mchange.v2.c3p0.impl.PoolBackedDataSourceBase.<clinit>(PoolBackedDataSourceBase.java:263)
...
15:22:43 main DEBUG (Slf4jMLog.java#log:198): The configuration file for resource identifier '/mchange-commons.properties' could not be found. Skipping.
java.io.FileNotFoundException: Resource not found at path '/mchange-commons.properties'.
	at com.mchange.v2.cfg.BasicPropertiesConfigSource.propertiesFromSource(BasicPropertiesConfigSource.java:64)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.firstInit(BasicMultiPropertiesConfig.java:185)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.<init>(BasicMultiPropertiesConfig.java:110)
	at com.mchange.v2.cfg.ConfigUtils.read(ConfigUtils.java:63)
	at com.mchange.v2.cfg.MConfig$CSManager.recreateFromKey(MConfig.java:153)
	at com.mchange.v1.cachedstore.NoCleanupCachedStore.find(NoCleanupCachedStore.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.mchange.v1.lang.Synchronizer$1.invoke(Synchronizer.java:58)
	at com.sun.proxy.$Proxy4.find(Unknown Source)
	at com.mchange.v2.cfg.MConfig.readVmConfig(MConfig.java:75)
	at com.mchange.v2.c3p0.cfg.C3P0Config.findLibraryMultiPropertiesConfig(C3P0Config.java:157)
	at com.mchange.v2.c3p0.cfg.C3P0Config.<clinit>(C3P0Config.java:143)
	at com.mchange.v2.c3p0.impl.PoolBackedDataSourceBase.<init>(PoolBackedDataSourceBase.java:54)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.<init>(AbstractPoolBackedDataSource.java:74)
	at com.mchange.v2.c3p0.AbstractComboPooledDataSource.<init>(AbstractComboPooledDataSource.java:142)
	at com.mchange.v2.c3p0.AbstractComboPooledDataSource.<init>(AbstractComboPooledDataSource.java:138)
	at com.mchange.v2.c3p0.ComboPooledDataSource.<init>(ComboPooledDataSource.java:47)
...
15:22:43 MLog-Init-Reporter DEBUG (Slf4jMLog.java#log:198): The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.
java.io.FileNotFoundException: HOCON lib (typesafe-config) is not available. Also, no resource available at '/reference,/application,/c3p0,/' for HOCON identifier 'hocon:/reference,/application,/c3p0,/'.
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.configSource(BasicMultiPropertiesConfig.java:86)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.firstInit(BasicMultiPropertiesConfig.java:184)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.<init>(BasicMultiPropertiesConfig.java:110)
	at com.mchange.v2.cfg.ConfigUtils.read(ConfigUtils.java:63)
	at com.mchange.v2.cfg.ConfigUtils.readVmConfig(ConfigUtils.java:115)
	at com.mchange.v2.cfg.MLogConfigSource.readVmConfig(MLogConfigSource.java:46)
	at com.mchange.v2.log.MLogConfig.refresh(MLogConfig.java:59)
	at com.mchange.v2.log.MLog.refreshConfig(MLog.java:59)
	at com.mchange.v2.log.MLog.<clinit>(MLog.java:51)
	at com.mchange.v2.naming.JavaBeanReferenceMaker.<clinit>(JavaBeanReferenceMaker.java:51)
	at com.mchange.v2.c3p0.impl.PoolBackedDataSourceBase.<clinit>(PoolBackedDataSourceBase.java:263)
...
15:22:43 MLog-Init-Reporter DEBUG (Slf4jMLog.java#log:198): The configuration file for resource identifier '/mchange-log.properties' could not be found. Skipping.
java.io.FileNotFoundException: Resource not found at path '/mchange-log.properties'.
	at com.mchange.v2.cfg.BasicPropertiesConfigSource.propertiesFromSource(BasicPropertiesConfigSource.java:64)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.firstInit(BasicMultiPropertiesConfig.java:185)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.<init>(BasicMultiPropertiesConfig.java:110)
	at com.mchange.v2.cfg.ConfigUtils.read(ConfigUtils.java:63)
	at com.mchange.v2.cfg.ConfigUtils.readVmConfig(ConfigUtils.java:115)
	at com.mchange.v2.cfg.MLogConfigSource.readVmConfig(MLogConfigSource.java:46)
	at com.mchange.v2.log.MLogConfig.refresh(MLogConfig.java:59)
	at com.mchange.v2.log.MLog.refreshConfig(MLog.java:59)
	at com.mchange.v2.log.MLog.<clinit>(MLog.java:51)
	at com.mchange.v2.naming.JavaBeanReferenceMaker.<clinit>(JavaBeanReferenceMaker.java:51)
	at com.mchange.v2.c3p0.impl.PoolBackedDataSourceBase.<clinit>(PoolBackedDataSourceBase.java:263)
...
15:22:43 main DEBUG (Slf4jMLog.java#log:198): The configuration file for resource identifier '/mchange-log.properties' could not be found. Skipping.
java.io.FileNotFoundException: Resource not found at path '/mchange-log.properties'.
	at com.mchange.v2.cfg.BasicPropertiesConfigSource.propertiesFromSource(BasicPropertiesConfigSource.java:64)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.firstInit(BasicMultiPropertiesConfig.java:185)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.<init>(BasicMultiPropertiesConfig.java:110)
	at com.mchange.v2.cfg.ConfigUtils.read(ConfigUtils.java:63)
	at com.mchange.v2.cfg.MConfig$CSManager.recreateFromKey(MConfig.java:153)
	at com.mchange.v1.cachedstore.NoCleanupCachedStore.find(NoCleanupCachedStore.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.mchange.v1.lang.Synchronizer$1.invoke(Synchronizer.java:58)
	at com.sun.proxy.$Proxy4.find(Unknown Source)
	at com.mchange.v2.cfg.MConfig.readVmConfig(MConfig.java:75)
	at com.mchange.v2.c3p0.cfg.C3P0Config.findLibraryMultiPropertiesConfig(C3P0Config.java:157)
	at com.mchange.v2.c3p0.cfg.C3P0Config.<clinit>(C3P0Config.java:143)
	at com.mchange.v2.c3p0.impl.PoolBackedDataSourceBase.<init>(PoolBackedDataSourceBase.java:54)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.<init>(AbstractPoolBackedDataSource.java:74)
	at com.mchange.v2.c3p0.AbstractComboPooledDataSource.<init>(AbstractComboPooledDataSource.java:142)
	at com.mchange.v2.c3p0.AbstractComboPooledDataSource.<init>(AbstractComboPooledDataSource.java:138)
	at com.mchange.v2.c3p0.ComboPooledDataSource.<init>(ComboPooledDataSource.java:47)
...
15:22:43 main DEBUG (Slf4jMLog.java#log:198): The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.
java.io.FileNotFoundException: HOCON lib (typesafe-config) is not available. Also, no resource available at '/reference,/application,/c3p0,/' for HOCON identifier 'hocon:/reference,/application,/c3p0,/'.
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.configSource(BasicMultiPropertiesConfig.java:86)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.firstInit(BasicMultiPropertiesConfig.java:184)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.<init>(BasicMultiPropertiesConfig.java:110)
	at com.mchange.v2.cfg.ConfigUtils.read(ConfigUtils.java:63)
	at com.mchange.v2.cfg.MConfig$CSManager.recreateFromKey(MConfig.java:153)
	at com.mchange.v1.cachedstore.NoCleanupCachedStore.find(NoCleanupCachedStore.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.mchange.v1.lang.Synchronizer$1.invoke(Synchronizer.java:58)
	at com.sun.proxy.$Proxy4.find(Unknown Source)
	at com.mchange.v2.cfg.MConfig.readVmConfig(MConfig.java:75)
	at com.mchange.v2.c3p0.cfg.C3P0Config.findLibraryMultiPropertiesConfig(C3P0Config.java:157)
	at com.mchange.v2.c3p0.cfg.C3P0Config.<clinit>(C3P0Config.java:143)
	at com.mchange.v2.c3p0.impl.PoolBackedDataSourceBase.<init>(PoolBackedDataSourceBase.java:54)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.<init>(AbstractPoolBackedDataSource.java:74)
	at com.mchange.v2.c3p0.AbstractComboPooledDataSource.<init>(AbstractComboPooledDataSource.java:142)
	at com.mchange.v2.c3p0.AbstractComboPooledDataSource.<init>(AbstractComboPooledDataSource.java:138)
	at com.mchange.v2.c3p0.ComboPooledDataSource.<init>(ComboPooledDataSource.java:47)
...
15:22:44 main DEBUG (Slf4jMLog.java#log:198): The configuration file for resource identifier '/c3p0.properties' could not be found. Skipping.
java.io.FileNotFoundException: Resource not found at path '/c3p0.properties'.
	at com.mchange.v2.cfg.BasicPropertiesConfigSource.propertiesFromSource(BasicPropertiesConfigSource.java:64)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.firstInit(BasicMultiPropertiesConfig.java:185)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.<init>(BasicMultiPropertiesConfig.java:110)
	at com.mchange.v2.cfg.ConfigUtils.read(ConfigUtils.java:63)
	at com.mchange.v2.cfg.MConfig$CSManager.recreateFromKey(MConfig.java:153)
	at com.mchange.v1.cachedstore.NoCleanupCachedStore.find(NoCleanupCachedStore.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.mchange.v1.lang.Synchronizer$1.invoke(Synchronizer.java:58)
	at com.sun.proxy.$Proxy4.find(Unknown Source)
	at com.mchange.v2.cfg.MConfig.readVmConfig(MConfig.java:75)
	at com.mchange.v2.c3p0.cfg.C3P0Config.findLibraryMultiPropertiesConfig(C3P0Config.java:157)
	at com.mchange.v2.c3p0.cfg.C3P0Config.<clinit>(C3P0Config.java:143)
	at com.mchange.v2.c3p0.impl.PoolBackedDataSourceBase.<init>(PoolBackedDataSourceBase.java:54)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.<init>(AbstractPoolBackedDataSource.java:74)
	at com.mchange.v2.c3p0.AbstractComboPooledDataSource.<init>(AbstractComboPooledDataSource.java:142)
	at com.mchange.v2.c3p0.AbstractComboPooledDataSource.<init>(AbstractComboPooledDataSource.java:138)
	at com.mchange.v2.c3p0.ComboPooledDataSource.<init>(ComboPooledDataSource.java:47)
...
15:22:44 main DEBUG (Slf4jMLog.java#log:198): The configuration file for resource identifier '/mchange-commons.properties' could not be found. Skipping.
java.io.FileNotFoundException: Resource not found at path '/mchange-commons.properties'.
	at com.mchange.v2.cfg.BasicPropertiesConfigSource.propertiesFromSource(BasicPropertiesConfigSource.java:64)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.firstInit(BasicMultiPropertiesConfig.java:185)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.<init>(BasicMultiPropertiesConfig.java:110)
	at com.mchange.v2.cfg.ConfigUtils.read(ConfigUtils.java:63)
	at com.mchange.v2.cfg.MConfig$CSManager.recreateFromKey(MConfig.java:153)
	at com.mchange.v1.cachedstore.NoCleanupCachedStore.find(NoCleanupCachedStore.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.mchange.v1.lang.Synchronizer$1.invoke(Synchronizer.java:58)
	at com.sun.proxy.$Proxy4.find(Unknown Source)
	at com.mchange.v2.cfg.MConfig.readVmConfig(MConfig.java:75)
	at com.mchange.v2.cfg.MConfig.readVmConfig(MConfig.java:81)
	at com.mchange.v2.resourcepool.BasicResourcePool.<clinit>(BasicResourcePool.java:60)
	at com.mchange.v2.resourcepool.BasicResourcePoolFactory.createPool(BasicResourcePoolFactory.java:340)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.<init>(C3P0PooledConnectionPool.java:671)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.createPooledConnectionPool(C3P0PooledConnectionPoolManager.java:952)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.getPool(C3P0PooledConnectionPoolManager.java:397)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.getPool(C3P0PooledConnectionPoolManager.java:414)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
...
15:22:44 main DEBUG (Slf4jMLog.java#log:198): The configuration file for resource identifier '/mchange-log.properties' could not be found. Skipping.
java.io.FileNotFoundException: Resource not found at path '/mchange-log.properties'.
	at com.mchange.v2.cfg.BasicPropertiesConfigSource.propertiesFromSource(BasicPropertiesConfigSource.java:64)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.firstInit(BasicMultiPropertiesConfig.java:185)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.<init>(BasicMultiPropertiesConfig.java:110)
	at com.mchange.v2.cfg.ConfigUtils.read(ConfigUtils.java:63)
	at com.mchange.v2.cfg.MConfig$CSManager.recreateFromKey(MConfig.java:153)
	at com.mchange.v1.cachedstore.NoCleanupCachedStore.find(NoCleanupCachedStore.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.mchange.v1.lang.Synchronizer$1.invoke(Synchronizer.java:58)
	at com.sun.proxy.$Proxy4.find(Unknown Source)
	at com.mchange.v2.cfg.MConfig.readVmConfig(MConfig.java:75)
	at com.mchange.v2.cfg.MConfig.readVmConfig(MConfig.java:81)
	at com.mchange.v2.resourcepool.BasicResourcePool.<clinit>(BasicResourcePool.java:60)
	at com.mchange.v2.resourcepool.BasicResourcePoolFactory.createPool(BasicResourcePoolFactory.java:340)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.<init>(C3P0PooledConnectionPool.java:671)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.createPooledConnectionPool(C3P0PooledConnectionPoolManager.java:952)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.getPool(C3P0PooledConnectionPoolManager.java:397)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.getPool(C3P0PooledConnectionPoolManager.java:414)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
...
15:22:44 main DEBUG (Slf4jMLog.java#log:198): The configuration file for resource identifier '/c3p0.properties' could not be found. Skipping.
java.io.FileNotFoundException: Resource not found at path '/c3p0.properties'.
	at com.mchange.v2.cfg.BasicPropertiesConfigSource.propertiesFromSource(BasicPropertiesConfigSource.java:64)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.firstInit(BasicMultiPropertiesConfig.java:185)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.<init>(BasicMultiPropertiesConfig.java:110)
	at com.mchange.v2.cfg.ConfigUtils.read(ConfigUtils.java:63)
	at com.mchange.v2.cfg.MConfig$CSManager.recreateFromKey(MConfig.java:153)
	at com.mchange.v1.cachedstore.NoCleanupCachedStore.find(NoCleanupCachedStore.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.mchange.v1.lang.Synchronizer$1.invoke(Synchronizer.java:58)
	at com.sun.proxy.$Proxy4.find(Unknown Source)
	at com.mchange.v2.cfg.MConfig.readVmConfig(MConfig.java:75)
	at com.mchange.v2.cfg.MConfig.readVmConfig(MConfig.java:81)
	at com.mchange.v2.resourcepool.BasicResourcePool.<clinit>(BasicResourcePool.java:60)
	at com.mchange.v2.resourcepool.BasicResourcePoolFactory.createPool(BasicResourcePoolFactory.java:340)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.<init>(C3P0PooledConnectionPool.java:671)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.createPooledConnectionPool(C3P0PooledConnectionPoolManager.java:952)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.getPool(C3P0PooledConnectionPoolManager.java:397)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.getPool(C3P0PooledConnectionPoolManager.java:414)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
...
15:22:44 main DEBUG (Slf4jMLog.java#log:198): The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.
java.io.FileNotFoundException: HOCON lib (typesafe-config) is not available. Also, no resource available at '/reference,/application,/c3p0,/' for HOCON identifier 'hocon:/reference,/application,/c3p0,/'.
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.configSource(BasicMultiPropertiesConfig.java:86)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.firstInit(BasicMultiPropertiesConfig.java:184)
	at com.mchange.v2.cfg.BasicMultiPropertiesConfig.<init>(BasicMultiPropertiesConfig.java:110)
	at com.mchange.v2.cfg.ConfigUtils.read(ConfigUtils.java:63)
	at com.mchange.v2.cfg.MConfig$CSManager.recreateFromKey(MConfig.java:153)
	at com.mchange.v1.cachedstore.NoCleanupCachedStore.find(NoCleanupCachedStore.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.mchange.v1.lang.Synchronizer$1.invoke(Synchronizer.java:58)
	at com.sun.proxy.$Proxy4.find(Unknown Source)
	at com.mchange.v2.cfg.MConfig.readVmConfig(MConfig.java:75)
	at com.mchange.v2.cfg.MConfig.readVmConfig(MConfig.java:81)
	at com.mchange.v2.resourcepool.BasicResourcePool.<clinit>(BasicResourcePool.java:60)
	at com.mchange.v2.resourcepool.BasicResourcePoolFactory.createPool(BasicResourcePoolFactory.java:340)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.<init>(C3P0PooledConnectionPool.java:671)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.createPooledConnectionPool(C3P0PooledConnectionPoolManager.java:952)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.getPool(C3P0PooledConnectionPoolManager.java:397)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.getPool(C3P0PooledConnectionPoolManager.java:414)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)

**Comment by swaldman** [comment]
In general, c3p0 is very verbose at DEBUG/FINE or TRACE/FINEST levels. The library is intended to be logged at INFO, with applications or better yet specific loggers at DEBUG only when you are actually debugging something (in which case, c3p0 errs on the side of overproviding information).

That said, these stack traces seem to have annoyed everyone, and as you say, they are not particularly informative. They're [already gone](https://github.com/swaldman/mchange-commons-java/commit/bfde81446d6c600d3433969fe1e2e0e9351d85b5) from the `mchange-commons-library` dependency that generates them, so they will be gone in the next version of c3p0.

**Comment by borislubimov** [comment]
Thank you!
