### ISSUE TITLE
c3p0-0.9.1.2 APPARENT DEADLOCK!!

### ISSUE THREAD

**Issue by yamadakin** [swaldman/c3p0#53]
I have a question about c3p0 APPARENT DEADLOCK!! WARN message.
How can I reappearance　this 「c3p0 APPARENT DEADLOCK」 in develop environment?
In production environment  I encountered APPARENT DEADLOCK and my Business Logic server(JbossAs5) hung infinitely.

How can I solve this probelm?
because can not set debugUnreturnedConnectionStackTraces and unreturnedConnectionTimeout
in production  environment , I want to reappearance this in local environment first.

c3p0's setting

Initializing c3p0 pool... com.mchange.v2.c3p0.PoolBackedDataSource@b4d742e8 [ connectionPoolDataSource -> com.mchange.v2.c3p0.WrapperConnectionPoolDataSource@62bd41a5 [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, debugUnreturnedConnectionStackTraces -> false, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, identityToken -> z8kflt99cezf5273d8x0|236ca3d6, idleConnectionTestPeriod -> 300, initialPoolSize -> 30, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 120, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 200, maxStatements -> 150, maxStatementsPerConnection -> 0, minPoolSize -> 30, nestedDataSource -> com.mchange.v2.c3p0.DriverManagerDataSource@5e8bee0f [ description -> null, driverClass -> null, factoryClassLocation -> null, identityToken -> z8kflt99cezf5273d8x0|3669818a, jdbcUrl -> jdbc:oracle:thin:@192.168.0.210:1521:ORCL, properties -> {user=******, password=******} ], preferredTestQuery -> null, propertyCycle -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false; userOverrides: {} ], dataSourceName -> null, factoryClassLocation -> null, identityToken -> z8kflt99cezf5273d8x0|1d0bc9e9, numHelperThreads -> 3 ]

my bl server log
2015/04/27-18:12:27.406 {WARN }com.mchange.v2.async.ThreadPoolAsynchronousRunner$DeadlockDetector@2797b60d -- APPARENT DEADLOCK!!! Creating emergency threads for unassigned pending tasks!
2015/04/27-18:12:27.412 {WARN }com.mchange.v2.async.ThreadPoolAsynchronousRunner$DeadlockDetector@2797b60d -- APPARENT DEADLOCK!!! Complete Status: 
	Managed Threads: 3
	Active Threads: 3
	Active Tasks: 
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StatementCloseTask@3054d932 (com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#1)
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StatementCloseTask@127f7a68 (com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#2)
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StatementCloseTask@6f3d4b54 (com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#0)
	Pending Tasks: 
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask@211cb0da
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@629ec931
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask@26aae28c
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask@1cff6929
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask@4451119e
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask@265bbf1c
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask@515fdaf0
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask@6c1eec4c
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask@622ba908
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask@20667e92
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask@28ffb3dc
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask@2b79458b
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask@26c4bef9
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask@3ed5e151
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@4bbbad11
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask@e5f5def
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask@170ffd48
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@1abd8dcc
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask@12a859cb
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@6a9f27fe
		com.mchange.v2.resourcepool.BasicResourcePool$1DestroyResourceTask@76facb61
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@4b3e8a4d
		com.mchange.v2.resourcepool.BasicResourcePool$1DestroyResourceTask@76e9ebd2
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@777964fb
		com.mchange.v2.resourcepool.BasicResourcePool$1DestroyResourceTask@42d4d804
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@23b210e3
		com.mchange.v2.resourcepool.BasicResourcePool$1DestroyResourceTask@7f72b963
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@44e953f3
		com.mchange.v2.resourcepool.BasicResourcePool$1DestroyResourceTask@328699dd
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@22df9615
		com.mchange.v2.resourcepool.BasicResourcePool$1DestroyResourceTask@4f64e96
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@46a15c65
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@bb90f1d
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@228f3eee
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@6a6c8cfb
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@7c9be952
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@5ff34667
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@5c934567
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@48b19cac
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@4a5057d
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@6e0b53ec
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@29b2e365
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@1f6f1146
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@34d71ac9
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@161f9d39
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@758b1487
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@7df0e75a
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@52e5064e
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@3a011566
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@1d23f94a
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@24c37838
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@1d09b763
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@68e6d379
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@a45e2bd
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@7228eb8f
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@5c8133d6
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@2672560c
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@1c6f418c
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@4c385ce9
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@85bec17
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@4ae8de4a
		com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@7e59f2b1
Pool thread stack traces:
	Thread[com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#1,5,jboss]
		oracle.jdbc.driver.OracleStatement.close(OracleStatement.java:1340)
		com.mchange.v1.db.sql.StatementUtils.attemptClose(StatementUtils.java:41)
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StatementCloseTask.run(GooGooStatementCache.java:404)
		com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
	Thread[com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#2,5,jboss]
		oracle.jdbc.driver.OracleStatement.close(OracleStatement.java:1340)
		com.mchange.v1.db.sql.StatementUtils.attemptClose(StatementUtils.java:41)
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StatementCloseTask.run(GooGooStatementCache.java:404)
		com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
	Thread[com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#0,5,jboss]
		oracle.jdbc.driver.OracleStatement.close(OracleStatement.java:1340)
		com.mchange.v1.db.sql.StatementUtils.attemptClose(StatementUtils.java:41)
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StatementCloseTask.run(GooGooStatementCache.java:404)
		com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)

jstack's result
 all worker thread wait in this way.

"WorkerThread#299[172.24.14.71:37031]" prio=10 tid=0x000000005bd64000 nid=0x7836 in Object.wait() [0x000000006fec4000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1315)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:557)
	- locked <0x0000000707860838> (a com.mchange.v2.resourcepool.BasicResourcePool)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:477)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:525)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:128)
	at org.hibernate.connection.C3P0ConnectionProvider.getConnection(C3P0ConnectionProvider.java:77)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:446)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:167)
	at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:142)
	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:85)
	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1397)
	at jp.co.tech.sbi.index.common.utils.HibernateContext.beginTranstraction(HibernateContext.java:20)
	at jp.co.tech.sbi.index.ocean.common.interceptor.CommonValidateInterceptor.invokeUnderTrace(CommonValidateInterceptor.java:73)
	at sun.reflect.GeneratedMethodAccessor733.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jboss.ejb3.interceptors.aop.EJB3InterceptorInterceptor.invoke(EJB3InterceptorInterceptor.java:83)
	at org.jboss.ejb3.interceptors.aop.EJB3InterceptorInterceptor.invoke(EJB3InterceptorInterceptor.java:70)
	at org.jboss.ejb3.interceptors.container.ContainerMethodInvocationWrapper.invokeNext(ContainerMethodInvocationWrapper.java:62)
	at org.jboss.ejb3.interceptors.aop.InvocationContextInterceptor$InvocationContext.proceed(InvocationContextInterceptor.java:138)
	at jp.co.tech.sbi.index.ocean.common.interceptor.OceanTraceInterceptor.invokeUnderTrace(OceanTraceInterceptor.java:76)
	at sun.reflect.GeneratedMethodAccessor732.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jboss.ejb3.interceptors.aop.EJB3InterceptorInterceptor.invoke(EJB3InterceptorInterceptor.java:83)
	at org.jboss.ejb3.interceptors.aop.EJB3InterceptorInterceptor.invoke(EJB3InterceptorInterceptor.java:70)
	at org.jboss.ejb3.interceptors.container.ContainerMethodInvocationWrapper.invokeNext(ContainerMethodInvocationWrapper.java:62)
	at org.jboss.ejb3.interceptors.aop.InterceptorSequencer.invoke(InterceptorSequencer.java:76)
	at org.jboss.ejb3.interceptors.aop.InterceptorSequencer.aroundInvoke(InterceptorSequencer.java:62)
	at sun.reflect.GeneratedMethodAccessor727.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jboss.aop.advice.PerJoinpointAdvice.invoke(PerJoinpointAdvice.java:174)
	at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
	at org.jboss.ejb3.interceptors.aop.InvocationContextInterceptor.fillMethod(InvocationContextInterceptor.java:72)
	at org.jboss.aop.advice.org.jboss.ejb3.interceptors.aop.InvocationContextInterceptor_z_fillMethod_684925142.invoke(InvocationContextInterceptor_z_fillMethod_684925142.java)
	at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
	at org.jboss.ejb3.interceptors.aop.InvocationContextInterceptor.setup(InvocationContextInterceptor.java:88)
	at org.jboss.aop.advice.org.jboss.ejb3.interceptors.aop.InvocationContextInterceptor_z_setup_684925142.invoke(InvocationContextInterceptor_z_setup_684925142.java)
	at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
	at org.jboss.ejb3.connectionmanager.CachedConnectionInterceptor.invoke(CachedConnectionInterceptor.java:62)
	at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
	at org.jboss.ejb3.entity.TransactionScopedEntityManagerInterceptor.invoke(TransactionScopedEntityManagerInterceptor.java:56)
	at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
	at org.jboss.ejb3.AllowedOperationsInterceptor.invoke(AllowedOperationsInterceptor.java:47)
	at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
	at org.jboss.ejb3.tx.NullInterceptor.invoke(NullInterceptor.java:42)
	at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
	at org.jboss.ejb3.stateless.StatelessInstanceInterceptor.invoke(StatelessInstanceInterceptor.java:68)
	at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
	at org.jboss.aspects.tx.TxPolicy.invokeInNoTx(TxPolicy.java:66)
	at org.jboss.ejb3.tx.TxInterceptor$NotSupported.invoke(TxInterceptor.java:114)
	at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
	at org.jboss.aspects.tx.TxPropagationInterceptor.invoke(TxPropagationInterceptor.java:76)
	at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
	at org.jboss.aspects.remoting.ReplicantsManagerInterceptor.invoke(ReplicantsManagerInterceptor.java:52)
	at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
	at org.jboss.ejb3.tx.NullInterceptor.invoke(NullInterceptor.java:42)
	at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
	at org.jboss.ejb3.security.Ejb3AuthenticationInterceptorv2.invoke(Ejb3AuthenticationInterceptorv2.java:182)
	at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
	at org.jboss.ejb3.ENCPropagationInterceptor.invoke(ENCPropagationInterceptor.java:41)
	at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
	at org.jboss.ejb3.BlockContainerShutdownInterceptor.invoke(BlockContainerShutdownInterceptor.java:67)
	at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
	at org.jboss.ejb3.core.context.CurrentInvocationContextInterceptor.invoke(CurrentInvocationContextInterceptor.java:47)
	at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
	at org.jboss.aspects.currentinvocation.CurrentInvocationInterceptor.invoke(CurrentInvocationInterceptor.java:67)
	at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
	at org.jboss.ejb3.interceptor.EJB3TCCLInterceptor.invoke(EJB3TCCLInterceptor.java:86)
	at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
	at org.jboss.ejb3.stateless.StatelessContainer.dynamicInvoke(StatelessContainer.java:363)
	at org.jboss.ejb3.session.InvokableContextClassProxyHack._dynamicInvoke(InvokableContextClassProxyHack.java:53)
	at org.jboss.aop.Dispatcher.invoke(Dispatcher.java:91)
	at org.jboss.aspects.remoting.AOPRemotingInvocationHandler.invoke(AOPRemotingInvocationHandler.java:82)
	at org.jboss.remoting.ServerInvoker.invoke(ServerInvoker.java:967)
	at org.jboss.remoting.transport.socket.ServerThread.completeInvocation(ServerThread.java:791)
	- locked <0x00000007844a6380> (a org.jboss.remoting.transport.socket.ServerThread)
	at org.jboss.remoting.transport.socket.ServerThread.processInvocation(ServerThread.java:744)
	at org.jboss.remoting.transport.socket.ServerThread.dorun(ServerThread.java:586)
	at org.jboss.remoting.transport.socket.ServerThread.run(ServerThread.java:234)

**Comment by swaldman** [comment]
`debugUnreturnedConnectionStackTraces` and `unreturnedConnectionTimeout` wouldn't help anyway. They don't have anything to do with APPARENT DEADLOCKs.

Your issue here is a known one: Oracle drivers are susceptible to hangs under certain Statement cache operations. To address this, beginning in c3p0 0.9.2, c3p0 offers a configuration parameter called [statementCacheNumDeferredCloseThreads](http://www.mchange.com/projects/c3p0/#statementCacheNumDeferredCloseThreads). You should upgrade (to c3p0 0.9.5, the current release version) and set this to 1. If you cannot do that, please turn Statement caching off by setting `maxStatements` to 0.

Your current use of the Statement cache may be harming rather than helping your performance. If your Connection pool is typically near `minPoolSize`, and if your app uses no more than roughly four prepared statements frequently, it may be fine, it may be helping. But if your Connection pool is more typically near its `maxPoolSize` of 300, the 120 is way too few Statements and you may be harming performance by forcing the Statement cache to churn. It's easiest to use `maxStatementsPerConnection`, and set that to roughly the number of PreparedStatements used frequently by your application.

**Comment by yamadakin** [comment]
Hi Mr swaldman.
Thank you for your answer.
With regard to my this failure,
My customers not permit me to version up c3p0 to  until the cause can investigate.

we want to reproduce the phenomenon in the local first,
after that we make c3p0 version up to 0.9.5 and 
confirm that the problem has been resolved after c3p0 version up.

Is there a way can reproducible this cause?
For example, by reducing the maxStatements,
run the SQL in multiple threads(many query) in order to churn through the Connections more frequently and quickly.
I am not good at English , so sorry for my poor English.

**Comment by swaldman** [comment]
Yes, if you want to reproduce the freeze locally, you've got the right strategy: keep maxStatements low to force Statement cache churn, and run a lot of concurrent clients doing real work with PreparedStatements with your Oracle thin driver. Also keep `numHelperThreads` low (though not lower I think than its default value of 3; that would be cheating.)

**Comment by adoukkali** [comment]
Hello swaldman, 
I am getting the same issue as "the apparent lock" mentionned here, where all threads were blocked on the following stack-trace :

- waiting on <0x00000005cc0a1d70> (a com.mchange.v2.resourcepool.BasicResourcePool)
at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1315)
at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:557)
- locked <0x00000005cc0a1d70> (a com.mchange.v2.resourcepool.BasicResourcePool)


I am using the version c3p0-0.9.1.2 with oracle 11, and  the statement cashing is not enabled (maxStatements and maxStatementsPerConnection are not set - default values are zero).

Do you have any recommendation how we can avoid this dead lock - as the upgrade to more recent version could not be afforded immediately

Thank you for you help.

**Comment by adoukkali** [comment]
Here is the configuration I am using :
Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 5, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, dataSourceName -> 2t6ceda01ide5cs1sskhp7|47ccf71d, debugUnreturnedConnectionStackTraces -> false, description -> Portal DB Connection, driverClass -> oracle.jdbc.driver.OracleDriver, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, identityToken -> 2t6ceda01ide5cs1sskhp7|47ccf71d, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, jdbcUrl -> jdbc:oracle:thin:@..., maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 600, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 90, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 10, numHelperThreads -> 3, numThreadsAwaitingCheckoutDefaultUser -> 0, preferredTestQuery -> null, properties -> {user=******, password=******}, propertyCycle -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false ]

**Comment by swaldman** [comment]
the most relevant debugging information is what comes in your logs after the APPARENT DEADLOCK messages. (it includes a list of the blocked active tasks causing the deadlock.)
