### ISSUE TITLE
Java 8 required

### ISSUE THREAD

**Issue by rotty3000** [swaldman/c3p0#57]
c3p0-0.9.5.1 is using Java 8 APIs. i.e. java.sql.SQLType

https://docs.oracle.com/javase/8/docs/api/java/sql/SQLType.html

It appears this is result of code generation.

e.g. `com/mchange/v2/c3p0/impl/NewProxyCallableStatement.java`

Was this intentional? It seems this is spec'd in JDBC 4.2 which comes with Java SE 8.

http://docs.oracle.com/javase/8/docs/technotes/guides/jdbc/

Perhaps this was accidental as I see the build.properties is still showing Java 6.

Is there a release of c3p0 which is JDBC 4.1 compliant?

**Comment by rotty3000** [comment]
FYI: http://docs.oracle.com/javase/8/docs/technotes/guides/jdbc/

**Comment by rotty3000** [comment]
Built with java 7 and the JDBC 4.2/Java 8 API methods are gone. Testing in our env to see if this solves the issue.

**Comment by ihostage** [comment]
JDK 7. I use Jackson2 for serialize ResultSet to JSON. And i have error:
```
java.lang.NoClassDefFoundError: java/sql/SQLType
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2570)
	at java.lang.Class.getDeclaredMethods(Class.java:1855)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClass._addMemberMethods(AnnotatedClass.java:601)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClass.resolveMemberMethods(AnnotatedClass.java:424)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClass.memberMethods(AnnotatedClass.java:251)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addMethods(POJOPropertiesCollector.java:474)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collect(POJOPropertiesCollector.java:234)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.collectProperties(BasicClassIntrospector.java:142)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forSerialization(BasicClassIntrospector.java:68)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forSerialization(BasicClassIntrospector.java:11)
	at com.fasterxml.jackson.databind.SerializationConfig.introspect(SerializationConfig.java:530)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:133)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1077)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1037)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:445)
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:599)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:93)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1837)
```

**Comment by dacr** [comment]
Got exactly the same issue with tomcat7/jre7, I've downgraded temporary c3p0 to 0.9.2.1 release. Would be possible for you to rebuild with java7 (and not java8 with java7 bytecode compatibility) and publish a new release ?

**Comment by kul** [comment]
:+1: please publish with either jdk 7 or -source -target flags.

**Comment by rotty3000** [comment]
It's been 5 years...
