### ISSUE TITLE
The connection is closed Exception 

### ISSUE THREAD

**Issue by bianjiang** [swaldman/c3p0#6]
I keep getting this error saying "A PooledConnection that has already signalled a Connection error is still in use!" I know this probably has nothing to do with c3p0, but is there a strategy to work around this? I did setup the test properties in c3p0.

Is there a way the connection can be just abandon when this exception happens
"com.mchange.v2.c3p0.impl.NewPooledConnection (NewPooledConnection.java:425) - [c3p0] A PooledConnection that has already signalled a Connection error is still in use!" ???

Thanks,

<bean id="pooledDataSource" class="com.mchange.v2.c3p0.ComboPooledDataSource"
        destroy-method="close">
        <property name="driverClass" value="${database.driverClassName}" />
        <property name="jdbcUrl" value="${database.url}" />
        <property name="user" value="${database.username}" />
        <property name="password" value="${database.password}" />
        <property name="minPoolSize" value="${database.minPoolSize}" />
        <property name="maxPoolSize" value="${database.maxPoolSize}" />
        <property name="acquireIncrement" value="5" />
        <property name="idleConnectionTestPeriod" value="1800" /> 
        <property name="preferredTestQuery" value="select 1;" />
        <property name="maxStatements" value="150" />
        <property name="maxIdleTime" value="3600" /> 
        <property name="testConnectionOnCheckin" value="true" />
        
        
    </bean>

Here is the exception:
2013-05-09 10:28:05,263 [http-nio-8443-exec-1] WARN  com.mchange.v2.c3p0.impl.NewPooledConnection (NewPooledConnection.java:425) - [c3p0] A PooledConnection that has already signalled a Connection error is still in use!
2013-05-09 10:28:05,263 [http-nio-8443-exec-1] WARN  com.mchange.v2.c3p0.impl.NewPooledConnection (NewPooledConnection.java:426) - [c3p0] Another error has occurred [ com.microsoft.sqlserver.jdbc.SQLServerException: The connection is closed. ] which will not be reported to listeners!
com.microsoft.sqlserver.jdbc.SQLServerException: The connection is closed.
    at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:190)
    at com.microsoft.sqlserver.jdbc.SQLServerConnection.checkClosed(SQLServerConnection.java:388)
    at com.microsoft.sqlserver.jdbc.SQLServerConnection.clearWarnings(SQLServerConnection.java:2145)
    at com.mchange.v2.c3p0.impl.NewProxyConnection.clearWarnings(NewProxyConnection.java:933)
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.handleAndClearWarnings(SqlExceptionHelper.java:268)
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logAndClearWarnings(SqlExceptionHelper.java:247)

**Comment by Seashor** [comment]
Hi, I just ran into  the same problem. Difference is that I'm using c3p0 throngh a 3rd party(same company) jar, the pooled connnection is managed by that jar. 

Just wonder, from a user perspective, what can i do to avoid such exception ? Or should i just wait the 3rd party team to optimize the connection managment  by add some connection test logic?

**Comment by swaldman** [comment]
There isn't much you can do about it, other than to try to fix what is likely poor Exception handling somewhere in your (or the 3rd party's) code, somewhere an Exception is caught and the Connection remains in use despite having become invalid.

(Your application is seeing all of the Exceptions c3p0 sees, if you are happy with how the application responds to Exceptions, you can just ignore the message. But you can't make it go away, alas, unless you turn off logging of warnings from `com.mchange.v2.c3p0.impl.NewPooledConnection`, which probably is not a great idea.)
