### ISSUE TITLE
A dead loop issue

### ISSUE THREAD

**Issue by solio** [swaldman/c3p0#73]
The stack is below(it's too long to show) ,it looks like call 'ComboPooledDataSource.toString' in somewhere,when datasource is close.But 'ComboPooledDataSource.toString' is not explicit called in my code.
`	at com.mchange.v2.c3p0.ComboPooledDataSource.toString(ComboPooledDataSource.java:539)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuffer.append(StringBuffer.java:265)
	- locked <0x00000006f7f4e338> (a java.lang.StringBuffer)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.assertCpds(AbstractPoolBackedDataSource.java:447)
	- locked <0x000000073cfd66d8> (a com.mchange.v2.c3p0.ComboPooledDataSource)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getPoolManager(AbstractPoolBackedDataSource.java:459)
	- locked <0x000000073cfd66d8> (a com.mchange.v2.c3p0.ComboPooledDataSource)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getNumThreadsAwaitingCheckoutDefaultUser(AbstractPoolBackedDataSource.java:203)
	at sun.reflect.GeneratedMethodAccessor1348.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.mchange.v2.beans.BeansUtils.extractAccessiblePropertiesToMap(BeansUtils.java:359)
	at com.mchange.v2.beans.BeansUtils.appendPropNamesAndValues(BeansUtils.java:324)
	at com.mchange.v2.c3p0.ComboPooledDataSource.toString(ComboPooledDataSource.java:539)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuffer.append(StringBuffer.java:265)
	- locked <0x00000006f7bad948> (a java.lang.StringBuffer)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.assertCpds(AbstractPoolBackedDataSource.java:447)
	- locked <0x000000073cfd66d8> (a com.mchange.v2.c3p0.ComboPooledDataSource)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getPoolManager(AbstractPoolBackedDataSource.java:459)
	- locked <0x000000073cfd66d8> (a com.mchange.v2.c3p0.ComboPooledDataSource)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getNumThreadsAwaitingCheckoutDefaultUser(AbstractPoolBackedDataSource.java:203)
	at sun.reflect.GeneratedMethodAccessor1348.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.mchange.v2.beans.BeansUtils.extractAccessiblePropertiesToMap(BeansUtils.java:359)
	at com.mchange.v2.beans.BeansUtils.appendPropNamesAndValues(BeansUtils.java:324)
	at com.mchange.v2.c3p0.ComboPooledDataSource.toString(ComboPooledDataSource.java:539)
`

**Comment by swaldman** [comment]
Can you please check what version of c3p0 you are using? Thanks.

**Comment by solio** [comment]
0.9.1.2
but I review the code,the latest version also has this issue,if call ComboPooledDataSource.toString

**Comment by swaldman** [comment]
Over the years there've been issues with `toString()` methods, but lots of them have been resolved, search the [CHANGELOG](https://github.com/swaldman/c3p0/blob/a88860a91a19fa80b825a0c00afce72ce7e46261/src/dist-static/CHANGELOG) for `toString` and you'll find several examples. I suspect the issue that you've found is among those resolved. If you observe the issue under 0.9.5.2, please let me know and I'll look into it.

**Comment by solio** [comment]
Yeah,I review the code again,it seems like the issue is not exist.Thank U.
