### ISSUE TITLE
How can reopen  when ComboPooledDataSource  close?

### ISSUE THREAD

**Issue by Dreampie** [swaldman/c3p0#78]
if I close `ComboPooledDataSource`, do something  and reget connection error:
```
Caused by: java.sql.SQLException: com.mchange.v2.c3p0.ComboPooledDataSource [ java.beans.IntrospectionException: java.lang.reflect.InvocationTargetException [numThreadsAwaitingCheckoutDefaultUser] ] has been closed() -- you can no longer use it.
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.assertCpds(AbstractPoolBackedDataSource.java:447) ~[c3p0-0.9.1.2.jar:0.9.1.2]
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getPoolManager(AbstractPoolBackedDataSource.java:459) ~[c3p0-0.9.1.2.jar:0.9.1.2]
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:128) ~[c3p0-0.9.1.2.jar:0.9.1.2]
	at cn.dreampie.orm.DataSourceMeta.getReadConnection(DataSourceMeta.java:108) ~[classes/:na]
	at cn.dreampie.orm.TableMetaBuilder.buildTableMeta(TableMetaBuilder.java:26) ~[classes/:na]
	... 16 common frames omitted
```

**Comment by swaldman** [comment]
Hi,

If you explicitly close a c3p0 `PooledDataSource` it is closed permanently and can't be revived. You may have meant to reset the DataSource rather than close it. See [soft and hard resets](http://www.mchange.com/projects/c3p0/apidocs/index.html).

If a `PooledDataSource` is broken temporarily because the database goes down, that's fine, just make sure you have [some strategy for Connection testing enabled](http://www.mchange.com/projects/c3p0/#simple_advice_on_connection_testing) and the DataSource will revive when the DBMS comes back up. But if you explicitly close the `DataSource`, it is dead.

The workaround is don't close the DataSource.

    smiles,
       Steve
